[package]
name = "static-page-builder"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
repository = "https://github.com/AlterionX/benxu-dev"

[dependencies]
maud = { version = "0.21.0", features = ["rocket"] }
chrono = { version = "0.4.7", features = ["serde"] }
serde = { version = "1.0.98", features = ["derive"] }
typed-builder = "0.3.0"

