[workspace]

members = [
    "server",
    # static pages
    "page-client",
    "wasm-script",
    # blog pages
    "blog-client",
    "blog-login-enum",
    "blog-db",
    # crypto suite extracted for convenience
    "crypto",
]

