[workspace]
resolver = "2"
members = [
    "servers/static-server",
    "clients/slideshow",
    "clients/blog",

    # Underlying libraries.
    "lib/shared-config",
    "lib/static-page-builder",
    "lib/web-sys-bridge",
]

[profile.wasm]
inherits = "release"
lto = true
opt-level = 3
