[package]
name = "blog-login-enum"
version = "0.1.1"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"

[dependencies.serde]
version = "1.0.106"
features = ["derive"]
[dependencies.uuid]
version = "0.8.1"
features = ["serde"]

