[package]
name = "blog-login-enum"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"

[dependencies.serde]
version = "1.0.101"
features = ["derive"]
[dependencies.uuid]
version = "0.7.4"
features = ["serde"]

