[package]
name = "blog-client"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A frontend for a blog utilizing WASM."
repository = "https://github.com/AlterionX/benxu-dev"

[lib]
crate-type = ["cdylib"]

[dependencies]
db-models = { package = "blog-db", version = "0.1.0", path = "../blog-db", default-features = false }
login-enum = { package = "blog-login-enum", version = "0.1.0", path = "../blog-login-enum" }

seed = { version = "0.4.1", git = "https://github.com/David-OConnor/seed.git" }
serde = { version = "1.0.101", features = ["derive"] }

boolinator = "2.4.0"
uuid = { version = "0.7.4", features = ["serde"] }
chrono = { version = "0.4.9", features = ["serde"] }
percent-encoding = "2.1.0"

futures = "^0.1.26"

wasm-bindgen = "0.2.50"
js-sys = "0.3.27"
[dependencies.web-sys]
version = "0.3.27"
features = [
      'Document',
      'Element',
      'HtmlElement',
      'Node',
      'NodeList',
      'Window',
      'CssStyleDeclaration',
      'EventTarget',
      'EventListener',
      'UiEvent',
      'DomTokenList',
      'Location',
      'History',
]

