[package]
name = "blog-client"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A frontend for a blog utilizing WASM."
repository = "https://github.com/AlterionX/benxu-dev"

[dependencies]
seed = "0.4.1"
serde = { version = "1.0.101", features = ["derive"] }
chrono = { version = "0.4.9", features = ["serde"] }
futures = "^0.1.26"
wasm-bindgen = "0.2.50"
js-sys = "0.3.27"
[dependencies.web-sys]
version = "0.3.27"
features = [
      'Document',
      'Element',
      'HtmlElement',
      'Node',
      'NodeList',
      'Window',
      'CssStyleDeclaration',
      'EventTarget',
      'EventListener',
      'UiEvent',
      'DomTokenList',
]

