[package]
name = "blog-client"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A frontend for a blog utilizing WASM."
repository = "https://github.com/AlterionX/benxu-dev"

[lib]
crate-type = ["cdylib"]

[dependencies.db-models]
package = "blog-db"
version = "0.1.0"
path = "../blog-db"
default-features = false
[dependencies.login-enum]
package = "blog-login-enum"
version = "0.1.0"
path = "../blog-login-enum"

[dependencies.seed]
version = "0.4.1"
git = "https://github.com/David-OConnor/seed.git"
[dependencies.serde]
version = "1.0.101"
features = ["derive"]

[dependencies.boolinator]
version = "2.4.0"
[dependencies.tap]
version = "0.4.0"
[dependencies.uuid]
version = "0.7.4"
features = ["serde"]
[dependencies.chrono]
version = "0.4.9"
features = ["serde"]
[dependencies.percent-encoding]
version = "2.1.0"

[dependencies.futures]
version = "^0.1.26"

[dependencies.wasm-bindgen]
version = "0.2.50"
[dependencies.js-sys]
version = "0.3.27"
[dependencies.web-sys]
version = "0.3.27"
features = [
      'Document',
      'Element',
      'HtmlElement',
      'Node',
      'NodeList',
      'Window',
      'CssStyleDeclaration',
      'EventTarget',
      'EventListener',
      'UiEvent',
      'DomTokenList',
      'Location',
      'History',
]

