[package]
name = "server"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
page-client = { path = "../page-client" }
wasm-script = { path = "../wasm-script" }
blog-client = { path = "../blog-client" }
blog-db = { path = "../blog-db" }
serde = { version = "1.0.98", features = ["derive"] }
serde_json = "1.0.40"
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["json", "serve", "diesel_postgres_pool"] }
maud = { version = "0.21.0", features = ["rocket"] }
chrono = { version = "0.4.7", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "chrono", "r2d2"] }
dotenv = "0.14.1"
ring = { version = "0.13.5", features = ["rsa_signing"] }
openssl = "0.10.24"
rand = "0.7.0"
hex = "0.3.2"
base64 = "0.10.1"
untrusted = "0.6.2"

