[package]
name = "benxu"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
page-client = { package = "benxu-page-client", path = "../page-client" }
wasm-script = { package = "benxu-wasm-script", path = "../wasm-script" }
blog-client = { package = "benxu-blog-client", path = "../blog-client" }
blog-db = { package = "benxu-blog-db", path = "../blog-db" }
crypto = { package = "bundled-crypto", path = "../crypto" }

# encoding, decoding, management
serde = { version = "1.0.100", features = ["derive"] }
serde_json = "1.0.40"
base64 = "0.10.1"
maud = { version = "0.21.0", features = ["rocket"] }

# server + db libs
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["uuid", "json", "serve", "diesel_postgres_pool"] }
diesel = { version = "1.4.2", features = ["postgres", "chrono", "r2d2"] }

# utility structs + fns
simple_logger = "1.3.0"
log = { version = "0.4", features = ["std", "serde"] }
tap = "0.4.0"
boolinator = "2.4.0"
chrono = { version = "0.4.9", features = ["serde"] }
rand = "0.7.0"
uuid = { version = "0.6.5", features = ["serde", "v4"] }

# config
dotenv = "0.14.1"

