[package]
name = "benxu"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
license = "MIT"
build = "build.rs"
description = "Joins a variety of components together to create a blog with a set of static pages."
repository = "https://github.com/AlterionX/benxu-dev"

[dependencies]
page-client = { package = "static-page-builder", version = "0.1.0", path = "../page-client" }
wasm-script = { package = "wasm-slideshow", version = "0.1.0", path = "../wasm-script" }
blog-client = { package = "blog-client", version = "0.1.0", path = "../blog-client" }
blog-db = { package = "blog-db", version = "0.1.0", path = "../blog-db", default-features = true }
crypto = { package = "bundled-crypto", version = "0.1.0", path = "../crypto" }

# encoding, decoding, management
serde = { version = "1.0.101", features = ["derive"] }
serde_json = "1.0.40"
base64 = "0.10.1"
maud = { version = "0.21.0", features = ["rocket"] }

# server + db libs
rocket = "0.4.2"
rocket_contrib = { version = "0.4.2", default-features = false, features = ["uuid", "json", "serve", "diesel_postgres_pool"] }
diesel = { version = "1.4.2", features = ["postgres", "chrono", "r2d2"] }

# utility structs + fns
simple_logger = "1.3.0"
log = { version = "0.4.8", features = ["std", "serde"] }
tap = "0.4.0"
boolinator = "2.4.0"
chrono = { version = "0.4.9", features = ["serde"] }
rand = "0.7.2"
uuid = { version = "0.7.4", features = ["serde"] }

# config
dotenv = "0.14.1"

