#![feature(type_ascription)]

//! A collection of types and migrations for use with diesel and postgresql specifically for my
//! website.

#[macro_use]
extern crate diesel;

pub mod models;
/// Auto generated by diesel. Reflects the database schema after applying all migrations in the
/// `migrations` folder.
pub mod schema;
