table! {
    /// Representation of the `google_sso` table.
    ///
    /// (Automatically generated by Diesel.)
    google_sso (id) {
        /// The `id` column of the `google_sso` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `created_at` column of the `google_sso` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `google_sso` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Uuid,
        /// The `updated_at` column of the `google_sso` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `updated_by` column of the `google_sso` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        updated_by -> Uuid,
        /// The `user_id` column of the `google_sso` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
    }
}

table! {
    /// Representation of the `passwords` table.
    ///
    /// (Automatically generated by Diesel.)
    passwords (id) {
        /// The `id` column of the `passwords` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `created_at` column of the `passwords` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `passwords` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Uuid,
        /// The `updated_at` column of the `passwords` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `updated_by` column of the `passwords` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        updated_by -> Uuid,
        /// The `user_id` column of the `passwords` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `hash` column of the `passwords` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        hash -> Text,
        /// The `salt` column of the `passwords` table.
        ///
        /// Its SQL type is `Varchar`.
        ///
        /// (Automatically generated by Diesel.)
        salt -> Varchar,
    }
}

table! {
    /// Representation of the `permissions` table.
    ///
    /// (Automatically generated by Diesel.)
    permissions (id) {
        /// The `id` column of the `permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `created_at` column of the `permissions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `permissions` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Nullable<Uuid>,
        /// The `user_id` column of the `permissions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        user_id -> Uuid,
        /// The `permission` column of the `permissions` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        permission -> Text,
    }
}

table! {
    /// Representation of the `posts` table.
    ///
    /// (Automatically generated by Diesel.)
    posts (id) {
        /// The `id` column of the `posts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `created_at` column of the `posts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `posts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Uuid,
        /// The `updated_at` column of the `posts` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `updated_by` column of the `posts` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        updated_by -> Uuid,
        /// The `published_at` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        published_at -> Nullable<Timestamptz>,
        /// The `published_by` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        published_by -> Nullable<Uuid>,
        /// The `archived_at` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        archived_at -> Nullable<Timestamptz>,
        /// The `archived_by` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        archived_by -> Nullable<Uuid>,
        /// The `deleted_at` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Timestamptz>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_at -> Nullable<Timestamptz>,
        /// The `deleted_by` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        deleted_by -> Nullable<Uuid>,
        /// The `title` column of the `posts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        title -> Text,
        /// The `body` column of the `posts` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        body -> Text,
        /// The `slug` column of the `posts` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        slug -> Nullable<Varchar>,
    }
}

table! {
    /// Representation of the `post_tag_junctions` table.
    ///
    /// (Automatically generated by Diesel.)
    post_tag_junctions (post_id, tag_id) {
        /// The `post_id` column of the `post_tag_junctions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        post_id -> Uuid,
        /// The `tag_id` column of the `post_tag_junctions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        tag_id -> Uuid,
        /// The `created_at` column of the `post_tag_junctions` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `post_tag_junctions` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Uuid,
    }
}

table! {
    /// Representation of the `tags` table.
    ///
    /// (Automatically generated by Diesel.)
    tags (id) {
        /// The `id` column of the `tags` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `created_at` column of the `tags` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `tags` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Uuid,
        /// The `name` column of the `tags` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        name -> Text,
        /// The `description` column of the `tags` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        description -> Text,
    }
}

table! {
    /// Representation of the `users` table.
    ///
    /// (Automatically generated by Diesel.)
    users (id) {
        /// The `id` column of the `users` table.
        ///
        /// Its SQL type is `Uuid`.
        ///
        /// (Automatically generated by Diesel.)
        id -> Uuid,
        /// The `user_name` column of the `users` table.
        ///
        /// Its SQL type is `Text`.
        ///
        /// (Automatically generated by Diesel.)
        user_name -> Text,
        /// The `created_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        created_at -> Timestamptz,
        /// The `created_by` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        created_by -> Nullable<Uuid>,
        /// The `updated_at` column of the `users` table.
        ///
        /// Its SQL type is `Timestamptz`.
        ///
        /// (Automatically generated by Diesel.)
        updated_at -> Timestamptz,
        /// The `updated_by` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Uuid>`.
        ///
        /// (Automatically generated by Diesel.)
        updated_by -> Nullable<Uuid>,
        /// The `first_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        first_name -> Nullable<Text>,
        /// The `last_name` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Text>`.
        ///
        /// (Automatically generated by Diesel.)
        last_name -> Nullable<Text>,
        /// The `email` column of the `users` table.
        ///
        /// Its SQL type is `Nullable<Varchar>`.
        ///
        /// (Automatically generated by Diesel.)
        email -> Nullable<Varchar>,
    }
}

joinable!(post_tag_junctions -> posts (post_id));
joinable!(post_tag_junctions -> tags (tag_id));
joinable!(post_tag_junctions -> users (created_by));
joinable!(tags -> users (created_by));

allow_tables_to_appear_in_same_query!(
    google_sso,
    passwords,
    permissions,
    posts,
    post_tag_junctions,
    tags,
    users,
);
