[package]
name = "blog-db"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"
license = "MIT"
description = "A set of migration scripts and structs for interacting with the database of a blog."
repository = "https://github.com/AlterionX/benxu-dev"

[dependencies]
chrono = { version = "0.4.7", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "chrono", "uuid"] }
serde = { version = "1.0.98", features = ["derive"] }
uuid = { version = "0.6.5", features = ["serde", "v4"] }
dotenv = "0.14.1"

