[package]
name = "blog-db"
version = "0.1.0"
authors = ["AlterionX <ben.xu.cs@gmail.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4.7", features = ["serde"] }
diesel = { version = "1.4.2", features = ["postgres", "chrono"] }
serde = { version = "1.0.98", features = ["derive"] }
dotenv = "0.14.1"

